#!/bin/bash
OMEIS_BASE=%OMEIS_BASE%
OME_BIN=%OME_BIN%
PIX_COMP=%PIX_COMP%
FILE_COMP=%FILE_COMP%
find $OMEIS_BASE/Files  -regex '.*/[0123456789]*' -atime +$FILE_COMP -type f -exec bzip2 -9 -f '{}' \;
find $OMEIS_BASE/Pixels -regex '.*/[0123456789]*' -atime +$PIX_COMP -type f -exec bzip2 -9 -f '{}' \;
