\c test


DROP SEQUENCE ANALYSIS_SEQ;
DROP TABLE ANALYSES;
CREATE SEQUENCE ANALYSIS_SEQ;
CREATE TABLE ANALYSES (
ANALYSIS_ID     INTEGER DEFAULT nextval ('ANALYSIS_SEQ') PRIMARY KEY,
PROGRAM_ID      INTEGER, -- REFERENCES PROGRAMS,
DATASET_ID      INTEGER, -- REFERENCES DATASETS,
EXPERIMENTER_ID INTEGER, -- REFERENCES EXPERIMENTERS,
TIMESTAMP       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DROP SEQUENCE FEATURE_SEQ;
DROP TABLE FEATURES;
CREATE SEQUENCE FEATURE_SEQ; 
CREATE TABLE FEATURES (
FEATURE_ID     INTEGER DEFAULT nextval ('FEATURE_SEQ'), -- All other FEATURE_IDs are foreign keys.
ANALYSIS_ID    INTEGER REFERENCES ANALYSES
);


INSERT INTO ANALYSES (ANALYSIS_ID,PROGRAM_ID,DATASET_ID,EXPERIMENTER_ID) VALUES (1,1,1,1);
INSERT INTO ANALYSES (ANALYSIS_ID,PROGRAM_ID,DATASET_ID,EXPERIMENTER_ID) VALUES (2,1,2,1);
INSERT INTO ANALYSES (ANALYSIS_ID,PROGRAM_ID,DATASET_ID,EXPERIMENTER_ID) VALUES (3,1,1,1);
INSERT INTO ANALYSES (ANALYSIS_ID,PROGRAM_ID,DATASET_ID,EXPERIMENTER_ID) VALUES (4,1,2,1);

INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (1,1);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (2,1);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (3,1);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (4,1);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (5,1);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (3,2);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (4,2);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (5,2);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (6,3);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (7,3);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (8,3);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (9,3);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (10,3);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (8,4);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (9,4);
--INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (10,4);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (3,3);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (4,3);
INSERT INTO FEATURES (FEATURE_ID,ANALYSIS_ID) VALUES (5,3);

CREATE INDEX FEAURES_FEATURE_ID_IDX ON FEATURES (FEATURE_ID);
CREATE INDEX FEAURES_ANALYSIS_ID_IDX ON FEATURES (ANALYSIS_ID);

-- Get all features not dependant on $analysisID - these are are the features safe to
-- delete once $analysisID expires.  Note that analyses other than $analysisID may show up
-- in this list.  Attributes from those analyses should also be deleted.
-- select f1.* from features f1 where not exists 
--  (select f2.feature_id from features f2 where
--	f1.feature_id=f2.feature_id and f2.analysis_id > $analysisID);
-- 
-- Add transaction support.
-- Add status field to analyses table.
-- Do not delete expired enalyses from analyses table - change status.
