#ifndef COMPRESSIONUTILS_H_
#define COMPRESSIONUTILS_H_

#include "DataGrid.h"

/*
class CompressionUtils
{
public:
	CompressionUtils() { };
	virtual ~CompressionUtils() { } ;

	static double deflate(ofstream & output, double * outarray, int size);
	static double * inflate(DataGrid * data, ifstream & input);

	static double none(ofstream & output, double * outarray, int size);
	static double zip(ofstream & output, double * outarray, int size);
	static double bZip(ofstream & output, double * outarray, int size);

	static double * bUnzip(DataGrid * data, ifstream & input);
	static double * unzip(DataGrid * data, ifstream & input);
	static double * unnone(DataGrid * data, ifstream & input);

};
*/

#endif /*COMPRESSIONUTILS_H_*/
