#!/usr/bin/perl -w
# src/util/ome

#-------------------------------------------------------------------------------
#
# Copyright (C) 2004 Open Microscopy Environment
#       Massachusetts Institute of Technology,
#       National Institutes of Health,
#       University of Dundee
#
#
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#-------------------------------------------------------------------------------


#-------------------------------------------------------------------------------
# Written by:    Tom Macura <tmacura@nih.gov>
#-------------------------------------------------------------------------------

use strict;
use OME;
our $VERSION = $OME::VERSION;

use OME::Util::OMECommander;

sub usage {
    OME::Util::Output->printHeader();
    print <<"USAGE";
Usage:
    ome <command> [<options>]
    ome help lists available commands.
USAGE
}

my $help;

if (scalar(@ARGV) <= 0) {
    &usage;
    exit;
} elsif ($ARGV[0] =~ /^(-V|--version)$/) {
    OME::Util::Output->printVersion();
    exit;
} elsif ($ARGV[0] =~ /^(-h|(--)?help)$/) {
    shift @ARGV;
    $help = 1;
} else {
    $help = 0;
}

OME::Util::OMECommander->handleCommand($help);



package OME::Util::Output;

use OME;

sub scriptName { return "ome"; }

sub printVersion {
    print "OME commander, version $OME::VERSION_STRING\n";
}

sub printHeader {
    &printVersion;
    print "\n";
}


1;

__END__

=head1 AUTHOR

Tom Macura <tmacura@nih.gov>,
National Institutes of Health

=head1 SEE ALSO

L<OME>, http://www.openmicroscopy.org/

=cut

