alter table FILENAME_PATTERN rename column BASE_NAME to OLD_BASE_NAME;
alter table FILENAME_PATTERN add column BASE_NAME text;
update FILENAME_PATTERN set BASE_NAME = OLD_BASE_NAME;


update DATA_COLUMNS set SQL_TYPE = 'string'
	where DATA_COLUMNS.DATA_COLUMN_ID = SEMANTIC_ELEMENTS.DATA_COLUMN_ID
		and SEMANTIC_ELEMENTS.SEMANTIC_TYPE_ID = SEMANTIC_TYPES.SEMANTIC_TYPE_ID
		and SEMANTIC_TYPES.NAME = 'FilenamePattern'
		and SEMANTIC_ELEMENTS.NAME='BaseName'
