=head1 NAME

OME Modules - Table of Contents

=head1 List of Modules

=head2 Database access

    OME::DBConnection
    OME::Factory
    OME::DBObject
    OME::Configuration

    OME::Project
    OME::Dataset
    OME::Feature
    OME::Image

    OME::LookupTable
        OME::LookupTable::Entry
    OME::DataTable
        OME::DataTable::Column
    OME::SemanticType
        OME::SemanticType::Element
        OME::SemanticType::Superclass
    OME::Module
        OME::Module::Category
        OME::Module::FormalInput
        OME::Module::FormalOutput
    OME::ModuleExecution
        OME::ModuleExecution::ActualInput
    OME::AnalysisChain
        OME::AnalysisChain::Node
        OME::AnalysisChain::Link
    OME::AnalysisChainExecution
        OME::AnalysisChainExecution::NodeExecution
    OME::AnalysisPath
        OME::AnalysisPath::Map

=over

=item Deprecated

    OME::Repository

=back

=head2 Session management

    OME::SessionManager
    OME::Session

=head2 Analysis engine

    OME::Analysis::CLIHandler
    OME::Analysis::FindBounds
    OME::Analysis::FindRatio
    OME::Analysis::FindSpotsHandler
    OME::Analysis::TrackSpotsHandler
    OME::Analysis::Handler
    OME::Analysis::NoopHandler
    OME::Tasks::AnalysisEngine

=head2 OME XML file format

    OME::Tasks::OMEImport
    OME::Tasks::OMEExport
    OME::ImportExport::SemanticTypeImport
    OME::ImportExport::SemanticTypeExport
    OME::Tasks::ProgramImport
    OME::Tasks::ChainImport
    OME::ImportExport::HierarchyImport
    OME::ImportExport::HierarchyExport

=head2 Proprietary image format importers

    OME::ImportExport::Importer
    OME::ImportExport::Import_reader
    OME::ImportExport::FileUtils
    OME::ImportExport::Params
    OME::ImportExport::PixWrapper
    OME::ImportExport::DVreader
    OME::ImportExport::STKreader
    OME::ImportExport::TIFFreader

=head2 Workflow layer

    OME::Tasks::ImageTasks

=head2 OME Remote Framework

    OME::Remote::Dispatcher
    OME::Remote::Prototypes
    OME::Remote::Utils

=head2 Web-based user interface

    OME::Web
    OME::Web::DatasetMetadata
    OME::Web::AddImageDataset
    OME::Web::DatasetComponents
    OME::Web::DatasetInProjects
    OME::Web::DatasetMetadata
    OME::Web::DatasetSearch
    OME::Web::DatasetSwitch
    OME::Web::DirTree
    OME::Web::DirTreeImport
    OME::Web::DirTreeImportSelect
    OME::Web::DirTreeSelect
    OME::Web::FindSpots
    OME::Web::GetGraphics
    OME::Web::GetInfo
    OME::Web::Helper::HTMLFormat
    OME::Web::Helper::JScriptFormat
    OME::Web::Home
    OME::Web::ImageSearch
    OME::Web::InfoDataset
    OME::Web::InfoProject
    OME::Web::Login
    OME::Web::Logout
    OME::Web::MakeNewProject
    OME::Web::ManageDataset
    OME::Web::ManageImage
    OME::Web::ManageProject
    OME::Web::ProjectDataset
    OME::Web::ProjectDatasetImage
    OME::Web::ProjectMetadata
    OME::Web::ProjectSearch
    OME::Web::ProjectSwitch
    OME::Web::SaveViewerSettings
    OME::Web::Thumb
    OME::Web::ThumbCurrentDataset
    OME::Web::ThumbCurrentProject
    OME::Web::ThumbWrite
    OME::Web::TitleBar
    OME::Web::Validation
    OME::Web::Viewer
    OME::Web::XMLFileExport 

=begin comment

    OME::Image::Pix
    OME::Research::AnalyseText
    OME::Research::SearchEngine
    OME::Research::SetStatement
    OME::SetDB
    OME::ViewerPreferences

unsorted:
	OME::Factory::Iterator
	OME::Image::Wavelengths
	OME::Image::LogicalChannel
	OME::Image::ImageFilesXYZWT
	OME::Image::DatasetMap
	OME::ImportExport::InsertFiles
	OME::ImportExport::ResolveFiles
	OME::LSID
	OME::Project::DatasetMap
	OME::Remote
	OME::Tasks::OMEXMLImportExport
	OME::Tasks::AEFacade
	OME::Tasks::ChainManager
	OME::Tasks::DatasetManager
	OME::Tasks::ImageManager
	OME::Tasks::OMEXMLImportExport
	OME::Tasks::ProjectManager
	OME::Tasks::Thumbnails


=end comment

=head1 AUTHOR

Douglas Creager (dcreager@alum.mit.edu)

