/*
 * org.openmicroscopy.ds.dto.HistoryLink
 *
 *------------------------------------------------------------------------------
 *
 *  Copyright (C) 2003-2004 Open Microscopy Environment
 *      Massachusetts Institute of Technology,
 *      National Institutes of Health,
 *      University of Dundee
 *
 *
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
 *  Written by:    Harry Hochheiser <hsh@nih.gov>
 *------------------------------------------------------------------------------
 */

package org.openmicroscopy.ds.dto;

import org.openmicroscopy.ds.dto.DataInterface;

/**
 * A link in a data history graph. Not autogenerated, as these thinks don't have 
 * independent existence in the OME database
 *
 * @author Harry Hochheiser (hsh@nih.gov)
 * @version 2.2 <small><i>(Internal: $Revision$ $Date$)</i></small>
 * @since OME2.2
 */

public interface HistoryLink
    extends DataInterface
{
    /** Criteria field name: <code>id</code> */
    public int getID();
    public void setID(int value);


    /** Criteria field name: <code>from_mex</code> */
    public ModuleExecution getFromModuleExecution();
    public void setFromModuleExecution(ModuleExecution value);

    /** Criteria field name: <code>from_output</code> */
    public FormalOutput getFromOutput();
    public void setFromOutput(FormalOutput value);

    /** Criteria field name: <code>to_mex</code> */
    public ModuleExecution getToModuleExecution();
    public void setToModuleExecution(ModuleExecution value);

    /** Criteria field name: <code>to_input</code> */
    public FormalInput getToInput();
    public void setToInput(FormalInput value);

}
