/*
 * org.openmicroscopy.ds.dto.HistoryLinkDTO
 *
 *------------------------------------------------------------------------------
 *
 *  Copyright (C) 2003-2004 Open Microscopy Environment
 *      Massachusetts Institute of Technology,
 *      National Institutes of Health,
 *      University of Dundee
 *
 *
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
 *  Written by:    Harry Hochheiser <hsh@nih.gov>
 *------------------------------------------------------------------------------
 */

package org.openmicroscopy.ds.dto;

import org.openmicroscopy.ds.dto.MappedDTO;
import java.util.Map;


/**
 * A link in a data history graph. Not autogenerated, as these thinks don't have 
 * independent existence in the OME database
 *
 * @author Harry Hochheiser (hsh@nih.gov)
 * @version 2.2 <small><i>(Internal: $Revision$ $Date$)</i></small>
 * @since OME2.2
 */

public class HistoryLinkDTO
    extends MappedDTO
	implements HistoryLink
{
	
	 public HistoryLinkDTO() { super(); }
	 public HistoryLinkDTO(Map elements) { super(elements); }

	 public String getDTOTypeName() { return "HistoryLink"; }
	 public Class getDTOType() { return HistoryLink.class; }

	 public int getID()
	 { return getIntElement("id"); }
	 public void setID(int value)
	 { setElement("id",new Integer(value)); }
	    
 
    /** Criteria field name: <code>from_mex</code> */
    public ModuleExecution getFromModuleExecution() {
    		return (ModuleExecution) getObjectElement("from_mex");
    }
    
    public void setFromModuleExecution(ModuleExecution value) {
    		setElement("from_mex",value);
    }

    /** Criteria field name: <code>from_output</code> */
    public FormalOutput getFromOutput() {
    		return (FormalOutput) getObjectElement("from_output");
    }
    public void setFromOutput(FormalOutput value) {
    		setElement("from_output",value);
    }

    /** Criteria field name: <code>to_mex</code> */
    public ModuleExecution getToModuleExecution() {
    		return (ModuleExecution) getObjectElement("to_mex");
    }
    
    public void setToModuleExecution(ModuleExecution value) {
    		setElement("to_mex",value);
    }

    /** Criteria field name: <code>to_input</code> */
    public FormalInput getToInput() {
    		return (FormalInput) getObjectElement("to_input");
    }
    
    public void setToInput(FormalInput value) {
    		setElement("to_input",value);
    }
    
    public void setMap(Map elements) {
    		super.setMap(elements);
    		parseChildElement("from_mex",ModuleExecutionDTO.class);
    		parseChildElement("from_output",FormalOutputDTO.class);
    		parseChildElement("to_mex",ModuleExecutionDTO.class);
    		parseChildElement("to_input",FormalInputDTO.class);
    }

}
