/*
 * org.openmicroscopy.ds.dto.HistoryDTO
 *
 *------------------------------------------------------------------------------
 *
 *  Copyright (C) 2003-2004 Open Microscopy Environment
 *      Massachusetts Institute of Technology,
 *      National Institutes of Health,
 *      University of Dundee
 *
 *
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with this library; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 *------------------------------------------------------------------------------
 */

/*------------------------------------------------------------------------------
 *  Written by:    Harry Hochheiser <hsh@nih.gov>
 *------------------------------------------------------------------------------
 */

package org.openmicroscopy.ds.dto;

import org.openmicroscopy.ds.dto.MappedDTO;
import org.openmicroscopy.ds.st.Experimenter;
import org.openmicroscopy.ds.st.ExperimenterDTO;

import java.util.List;
import java.util.Map;


/**
 * A data history graph. Not autogenerated, as these thinks don't have 
 * independent existence in the OME database
 *
 * @author Harry Hochheiser (hsh@nih.gov)
 * @version 2.2 <small><i>(Internal: $Revision$ $Date$)</i></small>
 * @since OME2.2
 */

public class HistoryDTO
    extends MappedDTO
	implements History
{
	
	 public HistoryDTO() { super(); }
	 public HistoryDTO(Map elements) { super(elements); }

	 public String getDTOTypeName() { return "History"; }
	 public Class getDTOType() { return History.class; }

	 public int getID()
	 { return getIntElement("id"); }
	 public void setID(int value)
	 { setElement("id",new Integer(value)); }
	    
	 public Experimenter getExperimenter()
	 { return (Experimenter) getObjectElement("experimenter"); }
	 
	 public void setExperimenter(Experimenter value)
	 { setElement("owner",value); }

	 public List getModuleExecutions()
	 { return (List) getObjectElement("module_executions"); }
	 public int countModuleExecutions()
	 { return countListElement("module_executions"); }

	 public List getLinks()
	 { return (List) getObjectElement("links"); }
	 public int countLinks()
	 { return countListElement("links"); }

	 
	 public void setMap(Map elements)
	 {
	    super.setMap(elements);
	    parseChildElement("experimenter",ExperimenterDTO.class);
	    parseListElement("module_executions",ModuleExecutionDTO.class);
	    parseListElement("links",HistoryLinkDTO.class);
	 }
}
