/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
/*                                                                               */
/*    Copyright (C) 2007 Open Microscopy Environment                             */
/*         Massachusetts Institue of Technology,                                 */
/*         National Institutes of Health,                                        */
/*         University of Dundee                                                  */
/*                                                                               */
/*                                                                               */
/*                                                                               */
/*    This library is free software; you can redistribute it and/or              */
/*    modify it under the terms of the GNU Lesser General Public                 */
/*    License as published by the Free Software Foundation; either               */
/*    version 2.1 of the License, or (at your option) any later version.         */
/*                                                                               */
/*    This library is distributed in the hope that it will be useful,            */
/*    but WITHOUT ANY WARRANTY; without even the implied warranty of             */
/*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU          */
/*    Lesser General Public License for more details.                            */
/*                                                                               */
/*    You should have received a copy of the GNU Lesser General Public           */
/*    License along with this library; if not, write to the Free Software        */
/*    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA  */
/*                                                                               */
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
/*                                                                               */
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
/* Written by:  Lior Shamir <shamirl [at] mail [dot] nih [dot] gov>              */
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/


#include "TrainingSet.h"

#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>

void randomize() 
{ 
time_t t; 
srand((unsigned) time(&t)); 
} 

int compute_features(char *root_dir, char *output_file,int class_num, int output_to_screen, int tiles,  int multi_process)
{   TrainingSet *ts;
     double res,per;
     ts=new TrainingSet(20000,class_num);
     ts->LoadFromDir(root_dir,0,output_to_screen,tiles,multi_process);
     ts->SaveToFile(output_file);
     return(1);
}     

int split_and_test(char *filename, int class_num, int method, int tiles, double split_ratio, double max_features)
{    TrainingSet *ts,*train,*test;

     ts=new TrainingSet(20000,class_num);
     ts->ReadFromFile(filename);
	 
     unsigned short confusion_matrix[(class_num+1)*(class_num+1)];
     double similarity_matrix[(class_num+1)*(class_num+1)];
     double res;

     train=new TrainingSet(ts->count,class_num);
     test=new TrainingSet(ts->count,class_num);
	 
     randomize();
     ts->split(split_ratio,train,test,tiles*tiles);     
     train->normalize();
     train->SetFisherScores(max_features,NULL);
     res=train->Test(test,method,confusion_matrix,similarity_matrix,tiles*tiles);
     ts->PrintConfusion(confusion_matrix,NULL,0);
     ts->PrintConfusion(NULL,similarity_matrix,0);     
     printf ("\nAccuracy: %f \n",res);
     return(1);
}


void ShowHelp()
{
   printf("\nLaboratory of Genetics/NIA/NIH \n");
   printf("usage: wndchrm [ train [-mtsh] <root directory> <output_file> ] | [ test [-trwnh] <input_file>] \n");
   printf("<root directory> is a directory that has the directories of the class images as subdirectories. Images should be stored in a directory structure such that each subdirectory contains the images of one class\n");
   printf("<input_file> is the file generated by the train command. \n");       
   printf("m - allow running multiple instances of this program (to be used on multiple-processor machines).\n");
   printf("tN - split the image into NxN tiles. The default is 1.\n");
   printf("w - use wnd-charm instead of wnn. \n");
   printf("s - silent mode.\n");   
   printf("r - the split ratio of the dataset to training/test subsets (0,1). The default is 0.25. \n");                  
   printf("n - maximum number of features out of the dataset (0,1) . The default is 0.15. \n");                  
   printf("h - show this note.\n\n");
   printf("examples: \n \t train: \n \t wndchrm train /path/to/dataset dataset.fit \n \t test: \n \t wndchrm test dataset.fit -n0.1 \n \n");
   printf("If you have any more questions, please email me (lior shamir) at <shamirl [at] mail [dot] nih [dot] gov> \n\n");
   return;
}


int main(int argc, char *argv[])
{   char *root_dir, *filename;
    int multi_processor=0;
    int arg_index=1;
    int tiles=1;
    int output_to_screen=1;
    int method=0;
    double split_ratio=0.25;
    double max_features=0.15;
    int train=0;
    int test=0;
    /* read parameters */
    if (argc<2)
    {  ShowHelp();
       return(1);
    }

    if (strcmp(argv[arg_index],"train")==0) train=1;
    if (strcmp(argv[arg_index],"test")==0) test=1;
    if (train==0 && test==0)
    {  ShowHelp();
       return(1);
    }
    arg_index++;
	  
    while (argv[arg_index][0]=='-')  
    {   if (strchr(argv[arg_index],'m')) multi_processor=1;
        if (strchr(argv[arg_index],'t')) tiles=atoi(&(strchr(argv[arg_index],'t')[1]));
        if (strchr(argv[arg_index],'s')) output_to_screen=0;
        if (strchr(argv[arg_index],'r')) split_ratio=atof(&(strchr(argv[arg_index],'r')[1]));                               
        if (strchr(argv[arg_index],'n')) max_features=atof(&(strchr(argv[arg_index],'n')[1]));                               
        if (strchr(argv[arg_index],'w')) method=1;
        if (strchr(argv[arg_index],'h'))                                
        {  ShowHelp();
            return(1);
        }         
        arg_index++;
     } 
     if (arg_index<argc) 
     {  if (train) 
        {  root_dir=argv[arg_index++];
            filename=argv[arg_index];
            compute_features(root_dir, filename,100, output_to_screen, tiles, multi_processor);
        }
        if (test)
       {   filename=argv[arg_index];
           split_and_test(filename, 100, method, tiles, split_ratio, max_features);       
       }
   }  

   return(1);
}
