# OME/Web/InfoDataset.pm

# Copyright (C) 2002 Open Microscopy Environment, MIT
# Author:  Jean-Marie Burel <j.burel@dundee.ac.uk>
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


package OME::Web::InfoDataset;

use strict;
use vars qw($VERSION);
$VERSION = '1.0';
use CGI;
use base qw(OME::Web);


sub getPageTitle {
	return "Open Microscopy Environment" ;
}


#sub createOMEPage{
sub getPageBody{
  my $self=shift;
  my $cgi=$self->CGI();
  my $body="";
  my $session=$self->Session();  
  my $usergpID=$cgi->url_param('UsergpID');
  if ( !defined $usergpID){
    die "Package needs UsergpID as url parameters. Neither was supplied. This message generated by ".(ref $self)."->createOMEPage().";	
  }
  if (defined $usergpID){
    my @datasets=$session->Factory()->findObjects("OME::Dataset",'group_id'=>$usergpID);

   # my @datasets=OME::Dataset->search( group_id => $usergpID);
    $body.=$cgi->h3("Description");
    $body.=format_popup();
    foreach (@datasets){
	$body.=format_dataset($_);
    }
    $body.=close_button();

  }
   
  return('HTML',$body);




}

#--------------------
#PRIVATE METHODS
#-------------------
sub format_dataset{
  my ($dataset)=@_;
  my $summary="";
  $summary .= "<NOBR><B>Name:</B> ".$dataset->name()."</NOBR><BR>" ;
  $summary .= "<NOBR><B>ID:</B> ".$dataset->dataset_id()."</NOBR><BR>" ;
  $summary .= "<B>Description:</B> ".$dataset->description()."<BR>" ;
  $summary .= "<NOBR><B>Locked:</B> ".($dataset->locked()?'YES':'NO')."</NOBR><br>";
  $summary .= "<NOBR><B>Owner:</B> ".$dataset->owner()->firstname()." ".$dataset->owner()->lastname()."</NOBR><BR>";
  $summary .="<NOBR><B>E-mail:</B><a href='mailto:".$dataset->owner()->email()."'>".$dataset->owner()->email()."</a></NOBR><BR>";
  $summary .="<NOBR><B>Nb Images in dataset:</B> ".$dataset->images()."</NOBR><BR>";
  $summary.=create_button($dataset->dataset_id());
  $summary .="<br><br>";

  return $summary;

}


sub create_button{
 my ($id)=@_;
 my $text="";
 $text.=<<END;
	<input type=button
	onclick="return OpenPopUpData($id)"
	value="View"
	name="submit">
END
 return $text;
}





sub close_button{
 my $text="";
 $text.=<<END;
	<input type=button
	onclick="window.close()"
	value="Close window">
END
 return $text;
}

sub format_popup{
  my ($text)=@_;
 $text.=<<ENDJS;
<script language="JavaScript">
<!--
var ID;
function OpenPopUpData(id) {
      ID=id;
	var OMEfile;
	var ImageViewer;
	OMEfile='/perl2/serve.pl?Page=OME::Web::GetGraphics&DatasetID='+ID;
	ImageViewer=window.open(
		OMEfile,
		"ImageViewer",
		"toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=500,height=500");
	ImageViewer.focus();
      return false;
}
-->
</script>
ENDJS

return $text;
}





1;


