# OME/Web/InfoProject.pm

# Copyright (C) 2002 Open Microscopy Environment, MIT
# Author:  Jean-Marie Burel <j.burel@dundee.ac.uk>
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


package OME::Web::InfoProject;

use strict;
use vars qw($VERSION);
$VERSION = '1.0';
use CGI;
use base qw(OME::Web);


sub getPageTitle {
	return "Open Microscopy Environment" ;
}


sub createOMEPage{
  my $self=shift;
  my $cgi=$self->CGI();
  my $body="";  
  my $usergpID=$cgi->url_param('UsergpID');
  

  if ( !defined $usergpID){
    die "Package needs UsergpID as url parameters. Neither was supplied. This message generated by ".(ref $self)."->createOMEPage().";	
  }
  if (defined $usergpID){
    my @projects=OME::Project->search( group_id => $usergpID);
    $body.=$cgi->h3("Description");
    foreach (@projects){
	$body.=format_project($_);
    }
    $body.=close_button();

  }
   
  return('HTML',$body);




}

#--------------------
#PRIVATE METHODS
#-------------------

sub format_project{
 my ($project,$cgi)=@_;
 my $summary="";
 $summary .= "<P><NOBR><B>Name:</B> ".$project->name()."</NOBR><BR>" ;
 $summary .= "<NOBR><B>ID:</B> ".$project->project_id()."</NOBR><BR>" ;
 $summary .= "<B>Description:</B> ".$project->description()."<BR>" ;
 $summary .="<b>Nb Datasets:</b> ".scalar($project->datasets())."<br></p>";
 return $summary ;

}

sub close_button{
 my $text="";
 $text.=<<END;
	<input type=button
	onclick="window.close()"
	value="Close window">
END
 return $text;
}






1;

