
# OME/AnalysisView.pm

# Copyright (C) 2002 Open Microscopy Environment, MIT
# Author:  Douglas Creager <dcreager@alum.mit.edu>
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


package OME::AnalysisView;

=head1 NAME

OME::AnalysisView - an analysis chain

OME::AnalysisView::Node - a node in the analysis chain

OME::AnalysisView::Link - a link connecting two nodes in the chain

=head1 DESCRIPTION

The C<AnalysisView> class represents analysis chains in OME.  Each
chain is a directed acyclic graph.  The nodes of the chain represent
analysis modules that must get executed.  The links of the chain
connect outputs of one node to inputs of another; they specify the
order in which modules are executed and the relationship between the
data generated by the nodes.  The nodes are represented by the
C<AnalysisView::Node> class; the links by the C<AnalysisView::Link>
class.

=cut

use strict;
our $VERSION = '1.0';

use OME::DBObject;
use base qw(OME::DBObject);

__PACKAGE__->table('analysis_views');
__PACKAGE__->sequence('analysis_view_seq');
__PACKAGE__->columns(Primary => qw(analysis_view_id));
__PACKAGE__->columns(Essential => qw(owner name locked));
__PACKAGE__->columns(Description => qw(description));
#__PACKAGE__->hasa('OME::Experimenter' => qw(owner));
__PACKAGE__->has_many('nodes',
                      'OME::AnalysisView::Node' => qw(analysis_view_id));
__PACKAGE__->has_many('links',
                      'OME::AnalysisView::Link' => qw(analysis_view_id));
__PACKAGE__->has_many('paths',
                      'OME::AnalysisPath' => qw(analysis_view_id));

=head1 METHODS (C<AnalysisView>)

The following methods are available to C<AnalysisView> in addition to
those defined by L<OME::DBObject>.

=head2 owner

	my $owner = $chain->owner();
	$chain->owner($owner);

Returns or sets the owner of this analysis chain.

=head2 name

	my $name = $chain->name();
	$chain->name($name);

Returns or sets the name of this analysis chain.

=head2 locked

	my $locked = $chain->locked();
	$chain->locked($locked);

Returns or sets whether this analysis chain is locked.

=head2 description

	my $description = $chain->description();
	$chain->description($description);

Returns or sets the description of this analysis chain.

=head2 nodes

	my @nodes = $chain->nodes();
	my $node_iterator = $chain->nodes();

Returns or iterates, depending on context, the nodes in the analysis
chain.

=head2 links

	my @links = $chain->links();
	my $link_iterator = $chain->links();

Returns or iterates, depending on context, the links in the analysis
chain.

=head2 paths

	my @paths = $chain->paths();
	my $path_iterator = $chain->paths();

Returns or iterates, depending on context, the data paths in the
analysis chain.

=cut

sub owner {
    my $self = shift;
    if (@_) {
        my $attribute = shift;
        die "Owner must be an Experimenter"
          unless $attribute->attribute_type()->name() eq "Experimenter";
        $self->_owner_accessor($attribute->id());
        return undef;
    } else {
        return $self->Session()->Factory()->loadAttribute("Experimenter",
                                                          $self->_owner_accessor());
    }
}



package OME::AnalysisView::Node;

use strict;
our $VERSION = '1.0';

use OME::DBObject;
use base qw(OME::DBObject);

__PACKAGE__->AccessorNames({
    analysis_view_id => 'analysis_view',
    program_id       => 'program'
    });

__PACKAGE__->table('analysis_view_nodes');
__PACKAGE__->sequence('analysis_view_nodes_seq');
__PACKAGE__->columns(Primary => qw(analysis_view_node_id));
__PACKAGE__->columns(Essential => qw(analysis_view_id program_id
                                     iterator_tag new_feature_tag));
__PACKAGE__->hasa('OME::AnalysisView' => qw(analysis_view_id));
__PACKAGE__->hasa('OME::Program' => qw(program_id));
__PACKAGE__->has_many('input_links',
                      'OME::AnalysisView::Link' => qw(to_node));
__PACKAGE__->has_many('output_links',
                      'OME::AnalysisView::Link' => qw(from_node));

=head1 METHODS (C<AnalysisView::Node>)

The following methods are available to C<AnalysisView::Node> in
addition to those defined by L<OME::DBObject>.

=head2 analysis_view

	my $analysis_view = $node->analysis_view();
	$node->analysis_view($analysis_view);

Returns or sets the analysis chain that this node belongs to.

=head2 program

	my $program = $node->program();
	$node->program($program);

Returns or sets the analysis module that this node represents.

=head2 iterator_tag

	my $iterator_tag = $node->iterator_tag();
	$node->iterator_tag($iterator_tag);

Returns or sets the iterator tag for this node.

=head2 new_feature_tag

	my $new_feature_tag = $node->new_feature_tag();
	$node->new_feature_tag($new_feature_tag);

Returns or sets the tag that any new features created by this module
will have.

=head2 input_links

	my @input_links = $node->input_links();
	my $input_link_iterator = $node->input_links();

Returns or iterates, depending on context, the links that provide
input to this node.

=head2 output_links

	my @output_links = $node->output_links();
	my $output_link_iterator = $node->output_links();

Returns or iterates, depending on context, the links that this node
provides output for.

=cut

package OME::AnalysisView::Link;

use strict;
our $VERSION = '1.0';

use OME::DBObject;
use base qw(OME::DBObject);

__PACKAGE__->AccessorNames({
    analysis_view_id => 'analysis_view'
    });

__PACKAGE__->table('analysis_view_links');
__PACKAGE__->sequence('analysis_view_links_seq');
__PACKAGE__->columns(Primary => qw(analysis_view_link_id));
__PACKAGE__->columns(Essential => qw(analysis_view_id
                                     from_node from_output
                                     to_node to_input));
__PACKAGE__->hasa('OME::AnalysisView' => qw(analysis_view_id));
__PACKAGE__->hasa('OME::AnalysisView::Node' => qw(from_node));
__PACKAGE__->hasa('OME::Program::FormalOutput' => qw(from_output));
__PACKAGE__->hasa('OME::AnalysisView::Node' => qw(to_node));
__PACKAGE__->hasa('OME::Program::FormalInput' => qw(to_input));

=head1 METHODS (C<AnalysisView::Link>)

The following methods are available to C<AnalysisView::Link> in
addition to those defined by L<OME::DBObject>.

=head2 analysis_view

	my $analysis_view = $link->analysis_view();
	$link->analysis_view($analysis_view);

Returns the analysis chain that this link belongs to.

=head2 from_node

	my $from_node = $link->from_node();
	$link->from_node($from_node);

Returns the node that this link receives data from.

=head2 from_output

	my $from_output = $link->from_output();
	$link->from_output($from_output);

Returns the formal output that this link receives data from.

=head2 to_node

	my $to_node = $link->to_node();
	$link->to_node($to_node);

Returns the node that this link sends data to.

=head2 to_input

	my $to_input = $link->to_input();
	$link->to_input($to_input);

Returns the formal input that this link sends data to.

=cut

1;


__END__

=head1 AUTHOR

Douglas Creager <dcreager@alum.mit.edu>,
Open Microscopy Environment, MIT

=cut

